basePath: /
consumes:
- application/json
definitions:
  Product:
    description: Product Product defines the structure for an API product
    properties:
      CreatedOn:
        description: created on
        type: string
      DeletedOn:
        description: deleted on
        type: string
      UpdatedOn:
        description: updated on
        type: string
      description:
        description: description
        type: string
        x-go-name: Description
      id:
        description: the id for this user
        format: int64
        minimum: 1
        type: integer
        x-go-name: ID
      name:
        description: name
        type: string
        x-go-name: Name
      price:
        description: price
        format: float
        type: number
        x-go-name: Price
      sku:
        description: s k u
        type: string
        x-go-name: SKU
    required:
    - id
    type: object
    x-go-package: ProductService/client/models
host: localhost
info:
  description: Documentation for Product API
  termsOfService: Handler for products
  title: Products API.
  version: 1.0.0
paths:
  /products:
    get:
      description: Return a list of products from the database
      operationId: GetProducts
      responses:
        "200":
          $ref: '#/responses/data.Product'
      tags:
      - productsResponse
  /products/{id}:
    delete:
      description: Return a list of products from the database
      operationId: DeleteProducts
      parameters:
      - description: The id of product to delete from the database
        format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "201":
          $ref: '#/responses/noContent'
      tags:
      - productsResponse
produces:
- application/json
responses:
  noContent:
    description: empty response
  productsResponse:
    description: A list of products
    schema:
      items:
        $ref: '#/definitions/Product'
      type: array
schemes:
- http
- https
swagger: "2.0"
