// Code generated by go-swagger; DO NOT EDIT.

package products_response

// This files was generated by the swagger tool.
// Editing this files might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteProductsReader is a Reader for the DeleteProducts structure.
type DeleteProductsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProductsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDeleteProductsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteProductsCreated creates a DeleteProductsCreated with default headers values
func NewDeleteProductsCreated() *DeleteProductsCreated {
	return &DeleteProductsCreated{}
}

/* DeleteProductsCreated describes a response with status code 201, with default header values.

empty response
*/
type DeleteProductsCreated struct {
}

func (o *DeleteProductsCreated) Error() string {
	return fmt.Sprintf("[DELETE /products/{id}][%d] deleteProductsCreated ", 201)
}

func (o *DeleteProductsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
