// Code generated by go-swagger; DO NOT EDIT.

package products_response

// This files was generated by the swagger tool.
// Editing this files might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteProductsParams creates a new DeleteProductsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteProductsParams() *DeleteProductsParams {
	return &DeleteProductsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteProductsParamsWithTimeout creates a new DeleteProductsParams object
// with the ability to set a timeout on a request.
func NewDeleteProductsParamsWithTimeout(timeout time.Duration) *DeleteProductsParams {
	return &DeleteProductsParams{
		timeout: timeout,
	}
}

// NewDeleteProductsParamsWithContext creates a new DeleteProductsParams object
// with the ability to set a context for a request.
func NewDeleteProductsParamsWithContext(ctx context.Context) *DeleteProductsParams {
	return &DeleteProductsParams{
		Context: ctx,
	}
}

// NewDeleteProductsParamsWithHTTPClient creates a new DeleteProductsParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteProductsParamsWithHTTPClient(client *http.Client) *DeleteProductsParams {
	return &DeleteProductsParams{
		HTTPClient: client,
	}
}

/* DeleteProductsParams contains all the parameters to send to the API endpoint
   for the delete products operation.

   Typically these are written to a http.Request.
*/
type DeleteProductsParams struct {

	/* ID.

	   The id of product to delete from the database

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete products params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProductsParams) WithDefaults() *DeleteProductsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete products params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProductsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete products params
func (o *DeleteProductsParams) WithTimeout(timeout time.Duration) *DeleteProductsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete products params
func (o *DeleteProductsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete products params
func (o *DeleteProductsParams) WithContext(ctx context.Context) *DeleteProductsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete products params
func (o *DeleteProductsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete products params
func (o *DeleteProductsParams) WithHTTPClient(client *http.Client) *DeleteProductsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete products params
func (o *DeleteProductsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete products params
func (o *DeleteProductsParams) WithID(id int64) *DeleteProductsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete products params
func (o *DeleteProductsParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteProductsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
